# Generated by Django 3.2.13 on 2023-03-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_profile_friend_profi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='profi',
            new_name='profile',
        ),
    ]
