# Generated by Django 3.2.13 on 2023-03-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_remove_friend_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
