# Generated by Django 3.2.13 on 2023-03-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20230312_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
