# Generated by Django 3.2.13 on 2023-03-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_alter_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
