# Generated by Django 3.2.13 on 2023-03-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_alter_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
