# Generated by Django 3.2.13 on 2023-02-20 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230220_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friends',
        ),
        migrations.AddField(
            model_name='friend',
            name='fri',
            field=models.ManyToManyField(related_name='fri', to=settings.AUTH_USER_MODEL),
        ),
    ]
