# Generated by Django 3.2.13 on 2023-02-22 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20230222_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fri',
        ),
        migrations.AddField(
            model_name='friend',
            name='fri',
            field=models.ManyToManyField(related_name='fri', to=settings.AUTH_USER_MODEL),
        ),
    ]
