# Generated by Django 3.2.13 on 2023-03-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_friend_prof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
