# Generated by Django 3.2.13 on 2023-03-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_delete_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='msg_receiver',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='msg_sender',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
