# Generated by Django 3.2.13 on 2023-03-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20230311_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='profile',
        ),
    ]
