# Generated by Django 3.2.13 on 2023-03-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20230311_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
