# Generated by Django 3.2.13 on 2023-02-19 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddField(
            model_name='friend',
            name='friends',
            field=models.ManyToManyField(related_name='my_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
