# Generated by Django 3.2.13 on 2023-02-19 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230219_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friends',
        ),
        migrations.AddField(
            model_name='friend',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
