# Generated by Django 3.2.13 on 2023-03-03 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20230303_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='fri',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='prof',
        ),
        migrations.AddField(
            model_name='friend',
            name='prof',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
