# Generated by Django 3.2.13 on 2023-03-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_friend_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='my_friends', to='users.Friend'),
        ),
    ]
